version: 1.0.{build}
environment:
  matrix:
    - qt: 5.7\msvc2013
    - qt: 5.7\msvc2013_64
    - qt: 5.7\msvc2015
    - qt: 5.7\msvc2015_64
    
install:
- git submodule update --init --recursive 
- set PATH=C:\Qt\%qt%\bin;%PATH%;
- qmake.exe -tp vc -r
build:
  parallel: true
  verbosity: minimal